name: Test

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: print to stdout, stderr
      run: |
        echo "output to stdout"
        echo "output to stderr" >&2

    - name: pytest
      run: |
        pytest ./tests/
