name: Test

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache datasets
      id: cache-datasets
      uses: actions/cache@v2
      with:
        path: ./datasets
        key: datasets-${{ hashFiles('tests/.download_datasets.py') }}

    - name: Download datasets
      run: |
        pwd
        python ./tests/.download_datasets.py

    - name: print to stdout, stderr
      run: |
        echo "output to stdout"
        echo "output to stderr" >&2

    - name: pytest
      run: |
        pytest ./tests/
